# 数据操作

In [1]:
import torch#导入torch的库

张量表示一个数值组成的数组，这个数组可能有多个维度

In [56]:
x = torch.arange(12)#表示生成一个从0到11的tensor数组，一共12个数
x#jupyter中可以不使用print()函数，直接输入变量名就可以完成打印，但每次只能打印一行
x#若输入不同行的两个变量名，则只打印靠下的变量

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的shape属性访问其形状和元素总数


In [57]:
x.shape#shape函数返回x的属性，即一个大小为12的torch

torch.Size([12])

In [4]:
x.numel()#numel()函数仅返回x中元素的数量

12

要改变一个张量的形状而不改变元素数量和值，可以调用reshape函数


In [5]:
X = x.reshape(3,4)#reshape()函数将x的形状从一个1×12的矩阵改写为一个3×4的矩阵
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [60]:
#需要注意的是，调用reshape()函数时不会向系统申请新的内存空间，所以对调用后的变量进行操作时，会对调用前的变量造成改变
a = torch.arange(12)
b = a.reshape(3,4)
b[:] = 1#[:]表示将b中的所有行上的值都赋值1
a, b#同一行可以打印多个变量

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]))

In [6]:
torch.zeros((2,3,4))#表示生成2个大小为3×4的全零矩阵，维度为3

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))#表示生成2个大小为3×4的全1矩阵，维度为3

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
#通过提供包含数值的python列表，为张量中元素赋值
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

常见的标准算术运算符（$+$、$-$、$*$、$/$、$**$），都可以被升级为按元素运算

In [9]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, x ** y#均为逐元素计算，例如x+y为[1.0+2, 2+2, 4+2, 8+2]

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [10]:
torch.exp(x)#也可以使用指数函数运算，exp(t)函数表示e^t，同样逐元素进行运算

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [11]:
#连接多个张量
X = torch.arange(12, dtype = torch.float32).reshape((3, 4))#参数dtype表示张量中的数值类型为float单精度型
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)#cat为连接两个张量的函数，其中参数dim=0表示按行连接（增加行），dim=1表示按列连接

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [12]:
X == Y#使用逻辑符号“==——相等”依次判断X和Y中数值的关系，相等返回True，否则返回False

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
X.sum()#sum()函数表示对张量中所有的values(值)求和

tensor(66.)

In [14]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [15]:
a+b#维度相同，形状不同，按每个维度的最大进行扩张（广播机制），即a,b中行的最大值为3行，列的最大值为2列，则a,b均复制为3×2的张量

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [16]:
#[,]为切片，逗号前表示行切片，逗号后表示列切片，如[1:3,2:]表示取出第二行到四行（从第0行开始进行切片操作，左闭右开区间）和第3列之后的所有元素
#可以使用[-1]选择最后一行元素，用[1:3]选择第二行和第三行元素
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [17]:
#使用切片操作将元素写入矩阵
X[1, 2] = 9#表示在X矩阵的第二行第三列的位置写入9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
X[0:2,:] = 12#将第1行和第二行的所有元素赋值12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [19]:
#运行一些操作会可能会导致为新结果分配内存
before = id(Y)#id类似C++里的指针，表示内存地址
Y = Y + X
id(Y) == before#逻辑关系表达式，表示Y=Y+X后的Y和一开始的Y的内存地址不相同

False

In [20]:
#借助中间变量，以执行原地操作
Z = torch.zeros_like(Y)#zeros_like()表示张量的形状等均与Y相同，元素值全为0
print('id(Z):',id(Z))#''里是原封不动打印出来的内容，“，”后面不加‘’的表示打印变量的values
Z[:] = X + Y#表示X+Y中的内容赋值给Z中所有的行
print('id(Z):',id(Z))

id(Z): 1392415756176
id(Z): 1392415756176


In [21]:
#如果后续计算中没有重复使用X，我们也可以使用X[:]= X + Y或X += Y来减少操作的内存开销
before = id(X)
X += Y#或X[:] = X + Y
id(X) == before

True

In [22]:
#转换为NumPy张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)#前者表示是numpy中的ndarray，后者为torch中的tensor

(numpy.ndarray, torch.Tensor)

In [23]:
#将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)#item() 函数通常用于从一个单元素数组中提取出该元素，并返回其对应的 Python 标量类型

(tensor([3.5000]), 3.5, 3.5, 3)

# 数据预处理

In [44]:
#创建一个人工数据集，储存在csv文件中（逗号分隔value）
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
#os.makedirs()用于递归的创建目录（包括所有必要的父级目录）。如果路径中某些目录不存在，会自动创建这些目录。
#os.path.join('..', 'data')：将 .. 和 data 路径组合起来，生成一个相对路径。这里的 .. 表示上一级目录，因此os.path.join('..', 'data') 生成的路径是“上一级目录中的 data 文件夹”。
#exist_ok=True：如果要创建的目录已经存在，设置 exist_ok=True 参数就不会引发错误。这确保了即使目录已经存在，程序也能继续执行。
data_file = os.path.join('..', 'data', 'house_tiny.csv')#data_file：将生成的路径赋值给变量 data_file，表示 house_tiny.csv 文件的路径。
#os.path.join('..', 'data', 'house_tiny.csv')：将多个路径元素组合成一个完整的文件路径。在这个例子中，将 ..（上一级目录）、data（文件夹）、house_tiny.csv（文件名）组合起来，生成了 ../data/house_tiny.csv 这个相对路径。

with open(data_file, 'w') as f:#open(data_file, 'w')：打开文件 data_file 进行写入操作。data_file 是之前定义的 house_tiny.csv 文件的路径，表示 ../data/house_tiny.csv。
#'w' 模式：表示以写入模式打开文件。如果文件不存在，会创建这个文件；如果文件已经存在，它会被清空，然后重新写入内容。
#with 语句：这是上下文管理器，用于确保文件在打开后能够正确关闭。即使在写入过程中发生错误，with 语句也会确保文件被正确关闭。
#as f：将打开的文件对象赋值给变量 f，方便后续操作对文件进行写入。
    f.write('NumRooms,Alley,Price\n')#列名
    f.write('NA,Pave,127500\n')#每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [45]:
import pandas as pd
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

为了处理缺失的数据，典型的方法包括**插值**和**删除**，这里我们考虑**插值**

In [51]:
# inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# inputs = inputs.fillna(inputs.mean())
# print(inputs)报错

inputs, outputs = data.iloc[:, 0:1], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
inputs = pd.concat([inputs, data.iloc[:,1]],axis=1)
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


对于inputs中的类别值或离散值，我们将“NaN”视为一个类别

In [52]:
inputs = pd.get_dummies(inputs, dummy_na = True, dtype=int)#dtype=int
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

现在inputs和outputs中所有条目都是数值类型，它们可以转换为张量格式

In [53]:
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))